name: Lint project and test

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: windows-latest
    
    env:
      Solution_Name: CCprojectTicTacToe.sln
      SQLCONNSTR_ADONETCONNECT: ${{ secrets.SQLCONNSTR_ADONETCONNECT }}
      
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore ./CCprojectTicTacToe/CCprojectTicTacToe.csproj

      - name: Build app
        run: dotnet build ./CCprojectTicTacToe/CCprojectTicTacToe.csproj --configuration Release --no-restore

      - name: Lint app (analyzers)
        run: dotnet format analyzers --verify-no-changes --verbosity diagnostic --severity info

      - name: Lint app (style)
        run: dotnet format style --verify-no-changes --verbosity diagnostic --severity info
